export const POST_GET_REQUEST = "POST_GET_REQUEST";
export const POST_GET_SUCCESS = "POST_GET_SUCCESS";
export const POST_GET_FAIL = "POST_GET_FAIL";
export const NEW_POST_ADD="NEW_POST_ADD"
export const POST_DELETE_UPDATE="POST_DELETE_UPDATE"
export const POST_LIKE_UPDATE="POST_LIKE_UPDATE"
export const POST_DISLIKE_UPDATE="POST_DISLIKE_UPDATE"

export const SINGLE_POST_DELETE_UPDATE="SINGLE_POST_DELETE_UPDATE"
export const SINGLE_POST_LIKE_UPDATE="SINGLE_POST_LIKE_UPDATE"
export const SINGLE_POST_DISLIKE_UPDATE="SINGLE_POST_DISLIKE_UPDATE"


export const POST_CREATE_REQUEST = "POST_CREATE_REQUEST";
export const POST_CREATE_SUCCESS = "POST_CREATE_SUCCESS";
export const POST_CREATE_FAIL = "POST_CREATE_FAIL";

export const POST_DELETE_REQUEST = "POST_DELETE_REQUEST";
export const POST_DELETE_SUCCESS = "POST_DELETE_SUCCESS";
export const POST_DELETE_FAIL = "POST_DELETE_FAIL";

export const POST_LIKE_REQUEST = "POST_LIKE_REQUEST";
export const POST_LIKE_SUCCESS = "POST_LIKE_SUCCESS";
export const POST_LIKE_FAIL = "POST_LIKE_FAIL";

export const POST_GET_BYID_REQUEST = "POST_GET_BYID_REQUEST";
export const POST_GET_BYID_SUCCESS = "POST_GET_BYID_SUCCESS";
export const POST_GET_BYID_FAIL = "POST_GET_BYID_FAIL";

export const POST_COMMENT_REQUEST = "POST_COMMENT_REQUEST";
export const POST_COMMENT_SUCCESS = "POST_COMMENT_SUCCESS";
export const POST_COMMENT_FAIL = "POST_COMMENT_FAIL";


export const POST_RESET= "POST_RESET";
